name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start docker container
        run: docker compose up -d

      - name: Check if container is running
        run: | 
            for i in {1..10}; do
                result=$(curl --silent -H "Accept: application/json" localhost:10000/api/hello)
                if ["$result" == '{"greeting":"hello API"}']; then
                    echo "Container is running and API is responding"
                    exit 0;
                fi
                echo "Waiting for container to start {$i}/10"
                sleep 1
            done
            echo "Container did not start in time"
            exit 1