name: smoke

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Open port 10000
        run: |
          sudo iptables -A INPUT  -p tcp --dport 10000 -j ACCEPT
      
      - name: Start docker container
        run: docker compose up -d

      - name: Wait for API to be ready and run smoke test
        run: |
          for i in {1..10}; do
            response=$(curl --silent --show-error --fail http://localhost:10000/api/hello || true)
            if [ "$response" = '{"greeting":"hello API"}' ]; then
              echo "Container is running and API is responding"
              exit 0
            fi
            echo "Waiting for container to start $i/10"
            sleep 2
          done
          echo "Container did not start in time"
          exit 1